"""Check the working-tree publication candidates; never stages, commits or pushes."""
from pathlib import Path
import ast,hashlib,json,re,subprocess
ROOT=Path(__file__).resolve().parents[1]

def main():
    names=subprocess.check_output(['git','ls-files','--cached','--others','--exclude-standard'],cwd=ROOT,text=True).splitlines()
    candidates={name for name in names if (ROOT/name).is_file()}
    problems=[];local_links=[];checked_links=0;syntax_count=0;hash_count=0
    for name in sorted(candidates):
        p=ROOT/name
        if p.stat().st_size>=100*1024*1024:problems.append({'file':name,'reason':'At or above 100MiB'})
        if name.startswith('results/vri_preparation/') or p.suffix in {'.pt','.npz','.mjb','.db','.sqlite','.sqlite3','.tex'}:
            problems.append({'file':name,'reason':'Unexpected application/raw artifact in candidates'})
        if p.suffix=='.py':
            try:ast.parse(p.read_text(),filename=name);syntax_count+=1
            except SyntaxError as e:problems.append({'file':name,'reason':'Python syntax: '+str(e)})
        if p.suffix in {'.py','.md','.json','.txt','.yaml','.yml','.csv','.log','.sh'}:
            text=p.read_text(errors='replace')
            tokens=[r'-----BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY-----',r'\bgh[pousr]_[A-Za-z0-9]{30,}\b',r'\bsk-[A-Za-z0-9]{32,}\b',r'\bAKIA[A-Z0-9]{16}\b']
            if any(re.search(pattern,text) for pattern in tokens):problems.append({'file':name,'reason':'Credential pattern; value redacted'})
        if p.suffix=='.md' and 'evidence' not in p.parts and 'source' not in p.parts:
            for target in re.findall(r'\]\(([^)]+)\)',p.read_text()):
                if target.startswith(('https://','http://','mailto:','#')):continue
                resolved=(p.parent/target.split('#')[0]).resolve();checked_links+=1
                if resolved==ROOT/'docs/PUBLICATION_CHECKS.json':continue  # Generated by this check.
                if not resolved.exists():problems.append({'file':name,'reason':'Missing Markdown target','target':target})
                elif resolved.is_relative_to(ROOT):
                    relative=str(resolved.relative_to(ROOT));public=relative in candidates or resolved.is_dir() and any(x.startswith(relative+'/') for x in candidates)
                    if not public:local_links.append({'file':name,'target':target})
    problems.extend(dict(x,reason='Local-only navigation target') for x in local_links)
    archives=[]
    for p in sorted((ROOT/'results').rglob('SHA256SUMS')):
        if 'vri_preparation' in p.parts:continue
        count=0
        for line in p.read_text().splitlines():
            if not line.strip():continue
            digest,rel=line.split(None,1);target=p.parent/rel.lstrip('*');count+=1
            if not target.is_file() or hashlib.sha256(target.read_bytes()).hexdigest()!=digest:problems.append({'file':str(p.relative_to(ROOT)),'reason':'Checksum mismatch','target':rel})
        archives.append({'manifest':str(p.relative_to(ROOT)),'files':count});hash_count+=count
    diff=subprocess.run(['git','diff','--check'],cwd=ROOT,capture_output=True,text=True)
    if diff.returncode:problems.append({'reason':'git diff --check failed','details':diff.stdout})
    ignored=[]
    for relative in ['results/vri_preparation/20261004/application_video_script.md','scripts/build_application_subtitles.py','code/day9/g1_balance/checkpoints/skills_sprint/20261004/sequence_retest/evaluation/case_01/trace.npz']:
        ok=subprocess.run(['git','check-ignore','-q',relative],cwd=ROOT).returncode==0;ignored.append({'path':relative,'ignored':ok})
        if not ok:problems.append({'file':relative,'reason':'Expected ignore rule absent'})
    report={'status':'PASS' if not problems else 'FAIL','date':'2026-10-04','scope':'Working-tree publication candidates; no Git mutation or robot performance experiment','candidate_files':len(candidates),'candidate_bytes':sum((ROOT/n).stat().st_size for n in candidates),'python_sources_parsed':syntax_count,'markdown_targets_checked':checked_links,'published_checksum_entries_checked':hash_count,'archives':archives,'ignore_checks':ignored,'problems':problems,'limits':['Limited credential pattern scan, not an exhaustive secret/history audit','Historical evidence snapshots intentionally retain runtime paths','No network/public-access check or self-contained simulator claim','No new license or hardware/robustness validation']}
    (ROOT/'docs/PUBLICATION_CHECKS.json').write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps({k:report[k] for k in ['status','candidate_files','python_sources_parsed','markdown_targets_checked','published_checksum_entries_checked','problems']}))
    if problems:raise SystemExit(1)

if __name__=='__main__':main()
